### PR TITLE
CI: replace travis with github actions

### PR DESCRIPTION
**Pull request by bilelmoussaoui**
an experiment to see if the github actions could work better

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
Note: the CI is super fast compared to what we currently have https://github.com/gtk-rs/graphene/actions/runs/311766145

**Comment by GuillaumeGomez** [comment]
You don't seem to run the examples, or did I miss it?

**Comment by bilelmoussaoui** [comment]
> You don't seem to run the examples, or did I miss it?

The examples4 repo is broken currently, I will add it back once the rest of gtk4 stuff are in

**Comment by bilelmoussaoui** [comment]
@GuillaumeGomez  It should be building the examples as well now

**Comment by GuillaumeGomez** [comment]
It doesn't run `build_travis.sh`. :p

**Comment by GuillaumeGomez** [comment]
Also it doesn't seem to build with different features. But not sure how important it is... And you forgot to add a backline at the end of the file. ;)

**Comment by bilelmoussaoui** [comment]
> Also it doesn't seem to build with different features. But not sure how important it is... And you forgot to add a backline at the end of the file. ;)

There are 0 features for gtk4 stuff currently so, I can enable the latest gio feature though if needed.

> It doesn't run `build_travis.sh`. :p

The build_travis.sh just setups the dependencies and nothing more?

**Comment by bilelmoussaoui** [comment]
And you forgot to add a backline at the end of the file. ;)

My bad, should be fixed

**Comment by sdroege** [comment]
Let's get this in then, @GuillaumeGomez said on IRC to see what I say on it and I say we should get this in to move forward. All the gtk4 crates are currently broken and CI won't pass, and blocking on everything to be ready at once is not going to be very productive.

**Pull request merged**
