### PR TITLE
Remove ununsed lazy_static dependency

### PR DESCRIPTION
**Pull request by sdroege**
@EPashkin @GuillaumeGomez

### CODE REVIEW

**Comment by sdroege** [comment]
```
error: failed to select a version for `gio`.

    ... required by package `gtk-rs-examples4 v0.0.1 (/home/travis/build/gtk-rs/graphene/_examples)`

versions that meet the requirements `*` are: 0.8.0

the package `gtk-rs-examples4` depends on `gio`, with features: `futures` but `gio` does not have these features.
```

@GuillaumeGomez something broken in other ways with the CI

**Comment by GuillaumeGomez** [comment]
The gtk-rs-examples4 has never been updated. Error comes from there. Will send a PR.

**Comment by sdroege** [comment]
This can probably be retried and merged now?

**Comment by GuillaumeGomez** [comment]
Restarted.

**Comment by sdroege** [comment]
@GuillaumeGomez green :)

**Comment by GuillaumeGomez** [comment]
Thanks!

**Pull request merged**
