### PR TITLE
CI: improvements

### PR DESCRIPTION
**Pull request by bilelmoussaoui**
- Adds a gtk-rs/checker job
- Use the common gtk4 docker image
- Adds a docs job to provide decent docs until there's a release of the crate

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
Once merged, for the docs, someone has to set the github pages's branch to gh-pages after a successful pipeline as the docs are built from the master branch for now

**Comment by bilelmoussaoui** [comment]
cc @sdroege @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
> Once merged, for the docs, someone has to set the github pages's branch to gh-pages after a successful pipeline as the docs are built from the master branch for now

You mean the on the `gtk-rs.org` website?

**Comment by bilelmoussaoui** [comment]
> You mean the on the `gtk-rs.org` website?

No, just from this repository settings, so that https://gtk-rs.github.io/graphene/graphene would work unless there's something else that could be done for the docs?

**Comment by sdroege** [comment]
That seems useful so that we also have docs (at a different place) for latest master and not just the stable docs.

**Review by sdroege — APPROVED** [review]

**Comment by bilelmoussaoui** [comment]
I'm going to go ahead and merge this one, I will do the same for the gtk4 crates

**Pull request merged**
